version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=exchange_rate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "exchange_rate", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  web:
    build: .
    image: web:latest
    environment:
      - SECRET_KEY=secret
      - POSTGRES_DB=exchange_rate
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=CurrencyExchange.settings
      - REDIS_URL=redis://redis:6379/
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["sh", "-c", "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  worker:
    build: .
    image: worker:latest
    environment:
      - SECRET_KEY=secret
      - POSTGRES_DB=exchange_rate
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=CurrencyExchange.settings
      - REDIS_URL=redis://redis:6379/
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    depends_on:
      - web
      - db
      - redis
    command: ["sh", "-c", "sleep 20 && celery -A CurrencyExchange worker -l info"]
    networks:
      - mynetwork

  beat:
    build: .
    image: beat:latest
    environment:
      - SECRET_KEY=secret
      - POSTGRES_DB=exchange_rate
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=CurrencyExchange.settings
      - REDIS_URL=redis://redis:6379/
      - CELERY_BROKER_URL=redis://redis:6379/
      - CELERY_RESULT_BACKEND=redis://redis:6379/
    depends_on:
      - web
      - db
      - redis
    command: ["celery", "-A", "CurrencyExchange", "beat", "-l", "info"]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge