# Generated by Django 4.2.7 on 2023-11-28 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Nazwa waluty"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="Kod waluty"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=10,
                        default=0,
                        max_digits=20,
                        verbose_name="Kurs waluty",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Czy aktywna"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Kursy walut",
                "ordering": ("code",),
            },
        ),
    ]
